#!/bin/bash
WALL=$(find /home/joerg/Pictures/Wallpaper/ -type f \( -name "*.jpg" -o -name "*.png" \) | shuf -n1)
hyprctl monitors | awk '/^Monitor/{print $2}' | while read -r monitor; do
    hyprctl hyprpaper wallpaper "$monitor,$WALL"
done
