preload = /home/joerg/Pictures/Wallpaper/cachyos/marat-gilyadzinov-MYadhrkenNg-unsplash.jpg
wallpaper = ,/home/joerg/Pictures/Wallpaper/cachyos/marat-gilyadzinov-MYadhrkenNg-unsplash.jpg

splash = false
ipc = on
