require("items.widgets.calendar")
require("items.widgets.volume")
require("items.widgets.cpu")
require("items.widgets.disk")
require("items.widgets.next_event")
require("items.widgets.weather")
require("items.widgets.now_playing")
